#!/usr/bin/env python3
import os
import wget
import tarfile
import subprocess
import requests
import shutil
import sys


def download_file(url, filename):
    """Downloads a file from the specified URL to the specified filename."""
    downloads_directory = os.path.join(os.path.expanduser('~'), 'Downloads')
    filepath = os.path.join(downloads_directory, filename)

    print('Downloading file...')
    response = requests.get(url)
    with open(filepath, 'wb') as file:
        file.write(response.content)
    print('Download complete.')

def install_application(filename):
    """Installs the application from the specified filename using a sudo command."""
    filepath = os.path.join(os.path.expanduser('~'), 'Downloads', filename)

    print('Installing application...')
    install_command = ['sudo', 'dpkg', '-i', filepath]
    subprocess.run(install_command, check=True)
    print('Installation complete.')

# Usage example
url = 'https://github.com/sparrowwallet/sparrow/releases/download/1.7.9/sparrow_1.7.9-1_amd64.deb'
filename = 'sparrow_1.7.9-1_amd64.deb'
download_file(url, filename)
install_application(filename)

def download_and_install_tor_browser():
    # Replace the URL with the latest version's URL
    url = "https://www.torproject.org/dist/torbrowser/12.5.5/tor-browser-linux64-12.5.5_ALL.tar.xz"
    download_dir = os.path.expanduser('~/Downloads')

    # Use wget to download the Tor Browser
    subprocess.run(["wget", url], cwd=download_dir)

    # Extract the downloaded tar.xz file
    tar_file = os.path.join(download_dir, "tor-browser-linux64-12.5.5_ALL.tar.xz")
    subprocess.run(["tar", "-xf", tar_file], cwd=download_dir)

    # Get the extracted folder name
    extracted_folder = "tor-browser"

    # Change to the extracted folder
    os.chdir(os.path.join(download_dir, extracted_folder))

    # Run the Tor Browser installation script
    subprocess.run(["./start-tor-browser.desktop", "--register-app"])

# Call the function to download and install Tor Browser
download_and_install_tor_browser()

# Define the URL to download the .deb file
url = "https://code.samourai.io/whirlpool/whirlpool-gui/uploads/fda2da816431c25598f532486ac0da09/whirlpool-gui_0.10.3_amd64.deb"

# Define the download directory
download_directory = os.path.expanduser("~/Downloads")

# Define the full path to save the .deb file
deb_file_path = os.path.join(download_directory, "whirlpool-gui_0.10.3_amd64.deb")

try:
    # Step 1: Use wget to download the .deb file to the ~/Downloads directory
    subprocess.run(["wget", url, "-P", download_directory], check=True)
    print(f".deb file from {url} downloaded to {download_directory} successfully.")

    # Step 2: Install the downloaded .deb package using sudo dpkg -i
    subprocess.run(["sudo", "dpkg", "-i", deb_file_path], check=True)
    print(f"Package {deb_file_path} installed successfully.")
except subprocess.CalledProcessError as e:
    print(f"Error running command: {e}")

